### ISSUE TITLE
改变图像集下拉列表选项顺序

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#12]
8到10首字母大写，后面字符小写
7是新加的，读取参数文件的ae和aae字段，这个我会单独穿件一个issue说明
原来的Absorption Optical Depth选项和图形都不要了，删掉

1、Size Distribution
2、Single Scattering Albedo
3、Refractive Index(Real)
4、Refractive Index(Imaginary)
5、Extinction Optical Depth
6、AAOD
7、AE/AAE     这个是新加的
8、Vol
9、Reff     原来的REF改成Reff
10、Rmea

**Comment by baikangwang** [comment]
> change naming

> sort

**Comment by baikangwang** [comment]
> Add Index property to control the sorting order

**Comment by baikangwang** [comment]
Resolved
