### ISSUE TITLE
修改Size Distribution图形

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#13]
1、标题改成“体积谱分布”，原来的“单位…”等全删掉
2、纵坐标的标题，把字符“SD”改成“Volume Size Distribution”
3、横轴添加下标题“Radius (μm)”
4、横轴坐标数值用对数（log）表示，为了将图形伸展开（这个我不知道行不行，你先试试，如果不行再想辙）

**Comment by baikangwang** [comment]
> ~~Change chart title~~

> ~~Change chart name~~

> ~~add Axis title~~

> change Axis X

**Comment by baikangwang** [comment]
> ~~Axis X shows as log(?)~~
> * Manually draw the Axis X labels
