### ISSUE TITLE
修改Refractive Index(Imaginary)

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#15]
1、纵轴标题将“（Imaginary）”删除
2、横轴添加下标题“Wavelength (μm)”

**Comment by baikangwang** [comment]
> change Axis Y title

> add Axis X title

**Comment by baikangwang** [comment]
Resolved

**Comment by baikangwang** [comment]
> ~~Will All of （Imaginary）be removed~~
> * just one
