### ISSUE TITLE
修改Extinction Optical Depth

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#17]
1、将EXT-T的tab纵轴标题的“EXT-T”删掉，在标题后加文字“(Total)”
2、将EXT-F的tab纵轴标题的“EXT-F”删掉，在标题后加文字“(Fine)”
3、将EXT-C的tab纵轴标题的“EXT-C”删掉，在标题后加文字“(Coarse)”
4、以上三个tab的横轴加标题“Wavelength (μm)”
5、将参数文件中的aod550数据加到ext-t的440后，也就是增加一个字段，注意只给ext-t的加

**Comment by baikangwang** [comment]
> change chart name of EXT-T, EXT-F and EXT-C

> Add Axis X title

> Add new field to ext-t

**Comment by baikangwang** [comment]
> 将参数文件中的aod550数据加到ext-t的440后，也就是增加一个字段，注意只给ext-t的加
> * it will support to one field mapping to multiple chartmapping object

**Comment by baikangwang** [comment]
Resolved

**Comment by baikangwang** [comment]
> ~~Does keep the labels on the tabs?~~
> * Yes
