### ISSUE TITLE
修改Single Scattering Albedo

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#18]
1、将SSA-T的tab纵轴标题的“SSA-T”删掉，在标题后加文字“(Total)”
2、将SSA-F的tab纵轴标题的“SSA-F”删掉，在标题后加文字“(Fine)”
3、将SSA-C的tab纵轴标题的“SSA-C”删掉，在标题后加文字“(Coarse)”
4、以上三个tab的横轴加标题“Wavelength (μm)”

**Comment by baikangwang** [comment]
> change chart name of SSA-T, SSA-F and SSA-C

> Add Axis X title

**Comment by baikangwang** [comment]
Resolved

**Comment by baikangwang** [comment]
> ~~以上三个tab的横轴加标题“Wavelength (μm)”~~

> ~~Does keep the label text on the tabs?~~
> * Yes
