### ISSUE TITLE
修改Reff

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#19]
这是以前的REF改名叫Reff
1、纵轴标题改为“Effective Radius (μm)”
2、主标题“有效半径”
3、横轴坐标上的reft改为“Total”，reff改为“Fine”，refc改为“Coarse”

**Comment by baikangwang** [comment]
> Axis Y title

> Axis X labels

> Chart title

**Comment by baikangwang** [comment]
Resolved. Need to check Axis Y title
