### ISSUE TITLE
修改Vol

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#20]
1、纵坐标标题改为“Volume (μm3)”    注：那个3是上标，我打不出来了，呵呵
2、横坐标volt改为Total，volf改为Fine，volc改为Coarse

**Comment by baikangwang** [comment]
> ~~Change Axis Y title~~

> ~~Change Axis X labels~~

**Comment by baikangwang** [comment]
> ~~How to change 3 to upper font~~
> * display as expression, μm^3

**Comment by baikangwang** [comment]
> ~~Extends the Axis X labels~~
> ![image](https://cloud.githubusercontent.com/assets/3970720/21446380/4ce19508-c900-11e6-95f3-7a93379502f9.png)
