### ISSUE TITLE
增加AE/AAE

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#23]
1、这个是新加的，读取参数文件的ae和aae字段
2、AE和AAE使用不同形状的点表示，之间不用连线，只显示点就可以，这个我拍张手绘图给你
![image](https://cloud.githubusercontent.com/assets/3970720/21448009/36ec62b0-c918-11e6-86cc-a3a5c6202411.png)

**Comment by baikangwang** [comment]
> ~~New chart~~

> ~~New chart type~~

> Need to consider show the legend of the point marks on the Title part

**Comment by baikangwang** [comment]
> New chart type

**Comment by baikangwang** [comment]
Depending on #28

**Comment by baikangwang** [comment]
Resolved
