### ISSUE TITLE
修改matlab和fortran程序

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#24]
1、找到代码 aod(1)<0.40，把0.40改成0，这个是为了让matlab处理的数据不存在NaN，这样你之前筛掉的NAN数据就不用筛了，小于0.40是空气质量良好，如果气象站点在空气比较好的城市，就会有没数据的可能，所以这个要放开，不筛掉NaN，试试让matlab把真实的值显示出来，这个虽然是matlab的，我今天已经跟他们确认，就是这段代码，一共两个地方，挨得也挺近，咱给改了吧，有问题也是他们让咱这样改的
2、最终的那个参数文件名字是Dubovik_stats_hangzhou_808_20160723，现在想把”Dubovik_stats_“去掉，文件名只要”hangzhou_808_20160723“这部分，这应该是改matlab程序

**Comment by baikangwang** [comment]
> ~~Modify matlab codes, change aod(1)<0.40 to aod(1)<0~~

> ~~Rename the bat file name Dubovik_stats_hangzhou_808_20160723 to hangzhou_808_20160723~~

**Comment by baikangwang** [comment]
Resolved
