### ISSUE TITLE
修改文件夹和文件名字

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#25]
1、将所有Aeronet都改成CIMEL，比如现在的AeronetData文件夹可以改成CIMELData，文件中包含Aeronet的也要改成CIMEL
2、在Data目录下有个KERNEL_aeronet_n22_83文件夹，这个中间的aeronet看看能不能改成Cimel，如果改这个应该是也要改fortran源码中的目录名
3、程序跑过后再Data目录下会有一个名为create_input_carsnet.exe的文件，”_carsnet“这部分能不能删除

**Comment by baikangwang** [comment]
> ~~Change Aeronet to CIMEL from all labels and namings~~

> ~~Change 'aeronet' in the folder naming KERNEL_aeronet_n22_83 folder to 'CIMEL'~~
>* KERNEL_aeronet_n22_83 is stored in the parameter file _Input.dat_, the file will updated when deploy

> ~~Remove '_carsnet' from the naming create_input_carsnet.exe~~

**Comment by baikangwang** [comment]
Resolved
