### ISSUE TITLE
改进数据处理功能

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#26]
现在的程序配置好了，在进行数据处理的时候，在界面上选择hangzhou，然后处理会自动读取hangzhou-808-1这个文件，应该是写死了，将来他们可能会在目录下放置hangzhou-808-2或hangzhou-808-3等等，这个要让用户选择

**Comment by baikangwang** [comment]
> ~~search all of (*.ALL & *.ALR) and let user to choose which will be processed
> change FDATA field to combo box to show all data file~~

**Comment by baikangwang** [comment]
Resolved
