### ISSUE TITLE
今天演示遇到的问题

### ISSUE THREAD

**Issue by edisonql** [baikangwang/CIMEL#27]
我在家测试好的程序，直接拿到气象局演示，发现参数路径都不对了，程序报错，我删了options目录下的两个json文件，还删除Data目录下产生的fortran文件和其他产生的文件，再重新配置参数目录，还是报错，最后还是拿了你给我的原始程序和目录才能正常跑起来，如果他们把这程序在一台机器上跑过了，再拷贝到另一台肯定会出现这情况，你看看这是什么问题

**Comment by baikangwang** [comment]
Resolved
